#!/usr/bin/env node
// Generador de PDF usando Puppeteer
// Uso: node generate_pdf_puppeteer.js <url> <output.pdf>
// Ejemplo: node generate_pdf_puppeteer.js "http://localhost:8185/admin/repairs.html?id=123" ./out/order-123.pdf

const fs = require('fs');
const path = require('path');

async function main(){
  const args = process.argv.slice(2);
  if(args.length < 2){
    console.error('Uso: node generate_pdf_puppeteer.js <url> <output.pdf> [repairId]');
    process.exit(2);
  }
  const [ url, out, repairIdArg ] = args;
  try{
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox','--disable-setuid-sandbox'] });
    const page = await browser.newPage();
    page.setViewport({ width: 1200, height: 900 });
    // proxy page console to node console for debugging
    page.on && page.on('console', msg => {
      try{ console.log('PAGE LOG:', msg.text()); }catch(e){}
    });
    console.log('Abriendo URL:', url);
    await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 });

    // If a repairId was provided (either as third arg or in URL query), try to open the print popup generated by the app
    const repairId = repairIdArg || (new URL(url, 'http://localhost')).searchParams.get('id') || null;

    let pdfPath = out;
    const outDir = path.dirname(out);
    if(!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

    if(repairId){
      console.log('Intentando generar PDF para repair id:', repairId);
      // Quick check: is the print function available on the page?
      try{
        const types = await page.evaluate(() => {
          return { openRepairReceiptPrint: typeof openRepairReceiptPrint, windowOpenRepair: typeof window.openRepairReceiptPrint };
        });
        console.log('Tipos en la página:', types);
      }catch(e){ console.log('No se pudo evaluar tipos en la página', e && e.message); }

      // Detect the real popup page via Puppeteer's targetcreated event instead
      // Load the receipt template from the admin HTML on disk and render it in page context
      const adminHtml = fs.readFileSync(path.join(__dirname, '..', 'public', 'admin', 'repairs.html'), 'utf8');
      const match = adminHtml.match(/popup\.document\.write\(`([\s\S]*?)`\);/m);
      if(!match){
        throw new Error('No se encontró la plantilla del comprobante en public/admin/repairs.html');
      }
      const tpl = match[1];

      const html = await page.evaluate(async (rid, tplStr) => {
        try{
          const resp = await fetch('/api/repairs.php?id=' + encodeURIComponent(rid), { cache: 'no-store' });
          const data = await resp.json().catch(()=>null) || {};
          window.currentRepairReceiptData = data;
        }catch(e){ window.currentRepairReceiptData = null; }

        let clientQrDataUrl = '';
        if(window.QRCode && window.currentRepairReceiptData && window.currentRepairReceiptData.orderNumber){
          try{
            clientQrDataUrl = await window.QRCode.toDataURL([
              'Orden: ' + (window.currentRepairReceiptData.orderNumber || ''),
              'Cliente: ' + (window.currentRepairReceiptData.customerName || ''),
              'Ingreso: ' + (window.currentRepairReceiptData.createdAt || ''),
              'Agenda: ' + (window.currentRepairReceiptData.scheduledAt || window.currentRepairReceiptData.createdAt || '')
            ].join('\n'), { width: 124, margin: 1 });
          }catch(e){ clientQrDataUrl = ''; }
        }

        const tpl = tplStr;
        const data = window.currentRepairReceiptData || {};
        const additionalContact = [data.contactName, data.contactPhone].filter(Boolean).join(' - ') || 'Sin contacto adicional';
        const agendaDate = window.formatReceiptDate ? window.formatReceiptDate(data.scheduledAt || data.createdAt) : (data.scheduledAt || data.createdAt || '');
        const createdDate = window.formatReceiptDate ? window.formatReceiptDate(data.createdAt) : (data.createdAt || '');
        const clientDisclaimer = [
          'Presupuesto valido por 15 dias corridos.',
          'Garantia de reparacion: 30 dias desde la entrega.',
          'Los equipos se reciben sin accesorios, memorias ni tarjeta SIM.',
          'Pasados 90 dias desde el aviso de retiro, no habra reclamo del equipo.',
          'Sin este comprobante no se podra retirar ningun equipo.',
          'SIN EXCEPCION.'
        ].map((line) => '<li>'+line+'</li>').join('');

        const html = (new Function('data','clientQrDataUrl','escapeHtml','formatReceiptDate','additionalContact','agendaDate','createdDate','clientDisclaimer', 'return `'+tpl+'`;'))(data, clientQrDataUrl, window.escapeHtml, window.formatReceiptDate, additionalContact, agendaDate, createdDate, clientDisclaimer);
        return html;
      }, repairId, tpl);
      const renderPage = await browser.newPage();
      await renderPage.setViewport({ width: 1200, height: 900 });
      await renderPage.setContent(html, { waitUntil: 'networkidle0', timeout: 60000 });
      await renderPage.waitForTimeout ? await renderPage.waitForTimeout(900) : await new Promise(r=>setTimeout(r,900));
      await renderPage.pdf({ path: pdfPath, format: 'A4', printBackground: true, margin: { top: '10mm', bottom: '10mm', left: '10mm', right: '10mm' } });
      console.log('PDF guardado en', pdfPath);
      try{ await renderPage.close(); }catch(e){}
      await browser.close();
      return;
    }

    // default: just print the main page
    await page.waitForTimeout(700);
    await page.pdf({ path: pdfPath, format: 'A4', printBackground: true, margin: { top: '10mm', bottom: '10mm', left: '10mm', right: '10mm' } });
    console.log('PDF guardado en', pdfPath);
    await browser.close();
  }catch(e){
    console.error('Error generando PDF:', e && e.message ? e.message : e);
    process.exit(1);
  }
}

main();
